# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('time', models.DateField(auto_now_add=True)),
                ('email', models.TextField()),
                ('amount', models.TextField()),
                ('cashtype', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
