# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iti', '0002_auto_20160308_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='id',
            new_name='trans_id',
        ),
    ]
