# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnzymeList',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('digest', models.TextField(blank=True, null=True)),
                ('start_pos', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enzyme_list',
                'managed': False,
            },
        ),
    ]
