# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipeg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chartDefault',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('value', models.FloatField()),
                ('group', models.IntegerField()),
            ],
        ),
    ]
